// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cms.proto

/*
Package cms is a generated protocol buffer package.

CMS

CMS Service API provides access to CMS entities and supports CMS use-cases

It is generated from these files:
	cms.proto

It has these top-level messages:
	Post
	PostRequest
	PostBySlugRequest
	GetPostsOptions
	CreatePostRequest
	CreatePostWithSlug
	UpdatePostRequest
	UpdatePostWithSlug
	Comment
	CommentRequest
	CreateCommentRequest
	UpdateCommentRequest
	User
	UserRequest
	CreateUserRequest
	CreateUserWithRole
	AuthUserRequest
	AccessToken
	StrAndHash
	Email
	UserPassword
*/
package cms

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"
import google_protobuf2 "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/mwitkow/go-proto-validators"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// UserRole
type UserRole int32

const (
	UserRole_UNKNOWN UserRole = 0
	UserRole_ADMIN   UserRole = 1
	UserRole_USER    UserRole = 2
)

var UserRole_name = map[int32]string{
	0: "UNKNOWN",
	1: "ADMIN",
	2: "USER",
}
var UserRole_value = map[string]int32{
	"UNKNOWN": 0,
	"ADMIN":   1,
	"USER":    2,
}

func (x UserRole) String() string {
	return proto.EnumName(UserRole_name, int32(x))
}
func (UserRole) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Post
type Post struct {
	Id         uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title      string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Content    string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	Created    string `protobuf:"bytes,4,opt,name=created" json:"created,omitempty"`
	LastEdited string `protobuf:"bytes,5,opt,name=last_edited,json=lastEdited" json:"last_edited,omitempty"`
	Published  bool   `protobuf:"varint,6,opt,name=published" json:"published,omitempty"`
	Slug       string `protobuf:"bytes,7,opt,name=slug" json:"slug,omitempty"`
}

func (m *Post) Reset()                    { *m = Post{} }
func (m *Post) String() string            { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()               {}
func (*Post) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Post) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Post) GetLastEdited() string {
	if m != nil {
		return m.LastEdited
	}
	return ""
}

func (m *Post) GetPublished() bool {
	if m != nil {
		return m.Published
	}
	return false
}

func (m *Post) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

// PostRequest
type PostRequest struct {
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *PostRequest) Reset()                    { *m = PostRequest{} }
func (m *PostRequest) String() string            { return proto.CompactTextString(m) }
func (*PostRequest) ProtoMessage()               {}
func (*PostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PostRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// PostRequestBySlug
type PostBySlugRequest struct {
	Slug string `protobuf:"bytes,1,opt,name=slug" json:"slug,omitempty"`
}

func (m *PostBySlugRequest) Reset()                    { *m = PostBySlugRequest{} }
func (m *PostBySlugRequest) String() string            { return proto.CompactTextString(m) }
func (*PostBySlugRequest) ProtoMessage()               {}
func (*PostBySlugRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PostBySlugRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

// GetPostsOptions
type GetPostsOptions struct {
	// when true, includes unpublished Posts in response (note: Authorization token with ADMIN role is required)
	IncludeUnPublished bool `protobuf:"varint,2,opt,name=includeUnPublished" json:"includeUnPublished,omitempty"`
}

func (m *GetPostsOptions) Reset()                    { *m = GetPostsOptions{} }
func (m *GetPostsOptions) String() string            { return proto.CompactTextString(m) }
func (*GetPostsOptions) ProtoMessage()               {}
func (*GetPostsOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetPostsOptions) GetIncludeUnPublished() bool {
	if m != nil {
		return m.IncludeUnPublished
	}
	return false
}

// CreatePostRequest
type CreatePostRequest struct {
	Title   string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *CreatePostRequest) Reset()                    { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()               {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreatePostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// CreatePostWithSlug
type CreatePostWithSlug struct {
	Post *CreatePostRequest `protobuf:"bytes,1,opt,name=post" json:"post,omitempty"`
	Slug string             `protobuf:"bytes,2,opt,name=slug" json:"slug,omitempty"`
}

func (m *CreatePostWithSlug) Reset()                    { *m = CreatePostWithSlug{} }
func (m *CreatePostWithSlug) String() string            { return proto.CompactTextString(m) }
func (*CreatePostWithSlug) ProtoMessage()               {}
func (*CreatePostWithSlug) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreatePostWithSlug) GetPost() *CreatePostRequest {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *CreatePostWithSlug) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

// UpdatePostRequest
type UpdatePostRequest struct {
	Id        uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	Published bool   `protobuf:"varint,4,opt,name=published" json:"published,omitempty"`
}

func (m *UpdatePostRequest) Reset()                    { *m = UpdatePostRequest{} }
func (m *UpdatePostRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatePostRequest) ProtoMessage()               {}
func (*UpdatePostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdatePostRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdatePostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *UpdatePostRequest) GetPublished() bool {
	if m != nil {
		return m.Published
	}
	return false
}

// UpdatePostWithSlug
type UpdatePostWithSlug struct {
	Post *UpdatePostRequest `protobuf:"bytes,1,opt,name=post" json:"post,omitempty"`
	Slug string             `protobuf:"bytes,2,opt,name=slug" json:"slug,omitempty"`
}

func (m *UpdatePostWithSlug) Reset()                    { *m = UpdatePostWithSlug{} }
func (m *UpdatePostWithSlug) String() string            { return proto.CompactTextString(m) }
func (*UpdatePostWithSlug) ProtoMessage()               {}
func (*UpdatePostWithSlug) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdatePostWithSlug) GetPost() *UpdatePostRequest {
	if m != nil {
		return m.Post
	}
	return nil
}

func (m *UpdatePostWithSlug) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

// Comment
type Comment struct {
	Id         uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Content    string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	Created    string `protobuf:"bytes,3,opt,name=created" json:"created,omitempty"`
	LastEdited string `protobuf:"bytes,4,opt,name=last_edited,json=lastEdited" json:"last_edited,omitempty"`
	UserId     string `protobuf:"bytes,5,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	PostId     string `protobuf:"bytes,6,opt,name=post_id,json=postId" json:"post_id,omitempty"`
}

func (m *Comment) Reset()                    { *m = Comment{} }
func (m *Comment) String() string            { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()               {}
func (*Comment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Comment) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Comment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Comment) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Comment) GetLastEdited() string {
	if m != nil {
		return m.LastEdited
	}
	return ""
}

func (m *Comment) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Comment) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

// CommentRequest
type CommentRequest struct {
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CommentRequest) Reset()                    { *m = CommentRequest{} }
func (m *CommentRequest) String() string            { return proto.CompactTextString(m) }
func (*CommentRequest) ProtoMessage()               {}
func (*CommentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CommentRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// CreateCommentRequest
type CreateCommentRequest struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	PostId  uint32 `protobuf:"varint,3,opt,name=post_id,json=postId" json:"post_id,omitempty"`
}

func (m *CreateCommentRequest) Reset()                    { *m = CreateCommentRequest{} }
func (m *CreateCommentRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCommentRequest) ProtoMessage()               {}
func (*CreateCommentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CreateCommentRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreateCommentRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateCommentRequest) GetPostId() uint32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

// UpdateCommentRequest
type UpdateCommentRequest struct {
	Id      uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *UpdateCommentRequest) Reset()                    { *m = UpdateCommentRequest{} }
func (m *UpdateCommentRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateCommentRequest) ProtoMessage()               {}
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *UpdateCommentRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateCommentRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// User
type User struct {
	Id         string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Email      string   `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Created    string   `protobuf:"bytes,3,opt,name=created" json:"created,omitempty"`
	LastActive string   `protobuf:"bytes,4,opt,name=last_active,json=lastActive" json:"last_active,omitempty"`
	Role       UserRole `protobuf:"varint,5,opt,name=role,enum=cms.UserRole" json:"role,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *User) GetLastActive() string {
	if m != nil {
		return m.LastActive
	}
	return ""
}

func (m *User) GetRole() UserRole {
	if m != nil {
		return m.Role
	}
	return UserRole_UNKNOWN
}

// UserRequest
type UserRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *UserRequest) Reset()                    { *m = UserRequest{} }
func (m *UserRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()               {}
func (*UserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *UserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// CreateUserRequest
type CreateUserRequest struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CreateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// CreateUserWithRole
type CreateUserWithRole struct {
	User *CreateUserRequest `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Role UserRole           `protobuf:"varint,2,opt,name=role,enum=cms.UserRole" json:"role,omitempty"`
}

func (m *CreateUserWithRole) Reset()                    { *m = CreateUserWithRole{} }
func (m *CreateUserWithRole) String() string            { return proto.CompactTextString(m) }
func (*CreateUserWithRole) ProtoMessage()               {}
func (*CreateUserWithRole) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *CreateUserWithRole) GetUser() *CreateUserRequest {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateUserWithRole) GetRole() UserRole {
	if m != nil {
		return m.Role
	}
	return UserRole_UNKNOWN
}

// AuthUserRequest
type AuthUserRequest struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *AuthUserRequest) Reset()                    { *m = AuthUserRequest{} }
func (m *AuthUserRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthUserRequest) ProtoMessage()               {}
func (*AuthUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *AuthUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AuthUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// AccessToken
type AccessToken struct {
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	TokenType   string `protobuf:"bytes,2,opt,name=token_type,json=tokenType" json:"token_type,omitempty"`
	ExpiresIn   uint32 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn" json:"expires_in,omitempty"`
}

func (m *AccessToken) Reset()                    { *m = AccessToken{} }
func (m *AccessToken) String() string            { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()               {}
func (*AccessToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *AccessToken) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AccessToken) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *AccessToken) GetExpiresIn() uint32 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

// StrAndHash
type StrAndHash struct {
	Str  string `protobuf:"bytes,1,opt,name=str" json:"str,omitempty"`
	Hash string `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
}

func (m *StrAndHash) Reset()                    { *m = StrAndHash{} }
func (m *StrAndHash) String() string            { return proto.CompactTextString(m) }
func (*StrAndHash) ProtoMessage()               {}
func (*StrAndHash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *StrAndHash) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func (m *StrAndHash) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

// Email
type Email struct {
	To      string `protobuf:"bytes,1,opt,name=to" json:"to,omitempty"`
	From    string `protobuf:"bytes,2,opt,name=from" json:"from,omitempty"`
	Subject string `protobuf:"bytes,3,opt,name=subject" json:"subject,omitempty"`
	Body    string `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
}

func (m *Email) Reset()                    { *m = Email{} }
func (m *Email) String() string            { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()               {}
func (*Email) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *Email) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Email) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Email) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Email) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

// UserPassword
type UserPassword struct {
	Password string `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
}

func (m *UserPassword) Reset()                    { *m = UserPassword{} }
func (m *UserPassword) String() string            { return proto.CompactTextString(m) }
func (*UserPassword) ProtoMessage()               {}
func (*UserPassword) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *UserPassword) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Post)(nil), "cms.Post")
	proto.RegisterType((*PostRequest)(nil), "cms.PostRequest")
	proto.RegisterType((*PostBySlugRequest)(nil), "cms.PostBySlugRequest")
	proto.RegisterType((*GetPostsOptions)(nil), "cms.GetPostsOptions")
	proto.RegisterType((*CreatePostRequest)(nil), "cms.CreatePostRequest")
	proto.RegisterType((*CreatePostWithSlug)(nil), "cms.CreatePostWithSlug")
	proto.RegisterType((*UpdatePostRequest)(nil), "cms.UpdatePostRequest")
	proto.RegisterType((*UpdatePostWithSlug)(nil), "cms.UpdatePostWithSlug")
	proto.RegisterType((*Comment)(nil), "cms.Comment")
	proto.RegisterType((*CommentRequest)(nil), "cms.CommentRequest")
	proto.RegisterType((*CreateCommentRequest)(nil), "cms.CreateCommentRequest")
	proto.RegisterType((*UpdateCommentRequest)(nil), "cms.UpdateCommentRequest")
	proto.RegisterType((*User)(nil), "cms.User")
	proto.RegisterType((*UserRequest)(nil), "cms.UserRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "cms.CreateUserRequest")
	proto.RegisterType((*CreateUserWithRole)(nil), "cms.CreateUserWithRole")
	proto.RegisterType((*AuthUserRequest)(nil), "cms.AuthUserRequest")
	proto.RegisterType((*AccessToken)(nil), "cms.AccessToken")
	proto.RegisterType((*StrAndHash)(nil), "cms.StrAndHash")
	proto.RegisterType((*Email)(nil), "cms.Email")
	proto.RegisterType((*UserPassword)(nil), "cms.UserPassword")
	proto.RegisterEnum("cms.UserRole", UserRole_name, UserRole_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hasher service

type HasherClient interface {
	Hash(ctx context.Context, in *google_protobuf2.StringValue, opts ...grpc.CallOption) (*google_protobuf2.StringValue, error)
	Validate(ctx context.Context, in *StrAndHash, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type hasherClient struct {
	cc *grpc.ClientConn
}

func NewHasherClient(cc *grpc.ClientConn) HasherClient {
	return &hasherClient{cc}
}

func (c *hasherClient) Hash(ctx context.Context, in *google_protobuf2.StringValue, opts ...grpc.CallOption) (*google_protobuf2.StringValue, error) {
	out := new(google_protobuf2.StringValue)
	err := grpc.Invoke(ctx, "/cms.Hasher/Hash", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hasherClient) Validate(ctx context.Context, in *StrAndHash, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/cms.Hasher/Validate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hasher service

type HasherServer interface {
	Hash(context.Context, *google_protobuf2.StringValue) (*google_protobuf2.StringValue, error)
	Validate(context.Context, *StrAndHash) (*google_protobuf1.Empty, error)
}

func RegisterHasherServer(s *grpc.Server, srv HasherServer) {
	s.RegisterService(&_Hasher_serviceDesc, srv)
}

func _Hasher_Hash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf2.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherServer).Hash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Hasher/Hash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherServer).Hash(ctx, req.(*google_protobuf2.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hasher_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StrAndHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HasherServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Hasher/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HasherServer).Validate(ctx, req.(*StrAndHash))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hasher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cms.Hasher",
	HandlerType: (*HasherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hash",
			Handler:    _Hasher_Hash_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _Hasher_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cms.proto",
}

// Client API for Emailer service

type EmailerClient interface {
	Send(ctx context.Context, in *Email, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type emailerClient struct {
	cc *grpc.ClientConn
}

func NewEmailerClient(cc *grpc.ClientConn) EmailerClient {
	return &emailerClient{cc}
}

func (c *emailerClient) Send(ctx context.Context, in *Email, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/cms.Emailer/Send", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Emailer service

type EmailerServer interface {
	Send(context.Context, *Email) (*google_protobuf1.Empty, error)
}

func RegisterEmailerServer(s *grpc.Server, srv EmailerServer) {
	s.RegisterService(&_Emailer_serviceDesc, srv)
}

func _Emailer_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Email)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailerServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Emailer/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailerServer).Send(ctx, req.(*Email))
	}
	return interceptor(ctx, in, info, handler)
}

var _Emailer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cms.Emailer",
	HandlerType: (*EmailerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Emailer_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cms.proto",
}

// Client API for CmsInternal service

type CmsInternalClient interface {
	// Gets the password of the provided User
	GetUserPassword(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserPassword, error)
	// Updates the LastActive field of the provided User
	UpdateUserLastActive(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type cmsInternalClient struct {
	cc *grpc.ClientConn
}

func NewCmsInternalClient(cc *grpc.ClientConn) CmsInternalClient {
	return &cmsInternalClient{cc}
}

func (c *cmsInternalClient) GetUserPassword(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserPassword, error) {
	out := new(UserPassword)
	err := grpc.Invoke(ctx, "/cms.CmsInternal/GetUserPassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsInternalClient) UpdateUserLastActive(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/cms.CmsInternal/UpdateUserLastActive", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CmsInternal service

type CmsInternalServer interface {
	// Gets the password of the provided User
	GetUserPassword(context.Context, *UserRequest) (*UserPassword, error)
	// Updates the LastActive field of the provided User
	UpdateUserLastActive(context.Context, *UserRequest) (*google_protobuf1.Empty, error)
}

func RegisterCmsInternalServer(s *grpc.Server, srv CmsInternalServer) {
	s.RegisterService(&_CmsInternal_serviceDesc, srv)
}

func _CmsInternal_GetUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsInternalServer).GetUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.CmsInternal/GetUserPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsInternalServer).GetUserPassword(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CmsInternal_UpdateUserLastActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsInternalServer).UpdateUserLastActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.CmsInternal/UpdateUserLastActive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsInternalServer).UpdateUserLastActive(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CmsInternal_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cms.CmsInternal",
	HandlerType: (*CmsInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserPassword",
			Handler:    _CmsInternal_GetUserPassword_Handler,
		},
		{
			MethodName: "UpdateUserLastActive",
			Handler:    _CmsInternal_UpdateUserLastActive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cms.proto",
}

// Client API for CmsAuth service

type CmsAuthClient interface {
	ActivateNewTokenForUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*AccessToken, error)
}

type cmsAuthClient struct {
	cc *grpc.ClientConn
}

func NewCmsAuthClient(cc *grpc.ClientConn) CmsAuthClient {
	return &cmsAuthClient{cc}
}

func (c *cmsAuthClient) ActivateNewTokenForUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*AccessToken, error) {
	out := new(AccessToken)
	err := grpc.Invoke(ctx, "/cms.CmsAuth/ActivateNewTokenForUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CmsAuth service

type CmsAuthServer interface {
	ActivateNewTokenForUser(context.Context, *User) (*AccessToken, error)
}

func RegisterCmsAuthServer(s *grpc.Server, srv CmsAuthServer) {
	s.RegisterService(&_CmsAuth_serviceDesc, srv)
}

func _CmsAuth_ActivateNewTokenForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsAuthServer).ActivateNewTokenForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.CmsAuth/ActivateNewTokenForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsAuthServer).ActivateNewTokenForUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _CmsAuth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cms.CmsAuth",
	HandlerType: (*CmsAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActivateNewTokenForUser",
			Handler:    _CmsAuth_ActivateNewTokenForUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cms.proto",
}

// Client API for Cms service

type CmsClient interface {
	// Setup the application
	Setup(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserRequest, error)
	// Check if application is setup
	IsSetup(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf2.BoolValue, error)
	// Create a post
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*PostRequest, error)
	// Get a post
	GetPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*Post, error)
	// Get a post (by slug)
	GetPostBySlug(ctx context.Context, in *PostBySlugRequest, opts ...grpc.CallOption) (*Post, error)
	// Update a post
	UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Delete a post
	DeletePost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Get all comments by post
	GetPostComments(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (Cms_GetPostCommentsClient, error)
	// Get all posts
	GetPosts(ctx context.Context, in *GetPostsOptions, opts ...grpc.CallOption) (Cms_GetPostsClient, error)
	// Create a user
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserRequest, error)
	// Get a user
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error)
	// Delete a user
	DeleteUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Get all comments by user
	GetUserComments(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (Cms_GetUserCommentsClient, error)
	// Create a comment
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CommentRequest, error)
	// Get a comment
	GetComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*Comment, error)
	// Update a comment
	UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Delete a comment
	DeleteComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Get all comments
	GetComments(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (Cms_GetCommentsClient, error)
	// Authorize as a user to get an access token
	AuthUser(ctx context.Context, in *AuthUserRequest, opts ...grpc.CallOption) (*AccessToken, error)
}

type cmsClient struct {
	cc *grpc.ClientConn
}

func NewCmsClient(cc *grpc.ClientConn) CmsClient {
	return &cmsClient{cc}
}

func (c *cmsClient) Setup(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserRequest, error) {
	out := new(UserRequest)
	err := grpc.Invoke(ctx, "/cms.Cms/Setup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) IsSetup(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf2.BoolValue, error) {
	out := new(google_protobuf2.BoolValue)
	err := grpc.Invoke(ctx, "/cms.Cms/IsSetup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*PostRequest, error) {
	out := new(PostRequest)
	err := grpc.Invoke(ctx, "/cms.Cms/CreatePost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) GetPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := grpc.Invoke(ctx, "/cms.Cms/GetPost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) GetPostBySlug(ctx context.Context, in *PostBySlugRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := grpc.Invoke(ctx, "/cms.Cms/GetPostBySlug", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/cms.Cms/UpdatePost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) DeletePost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/cms.Cms/DeletePost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) GetPostComments(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (Cms_GetPostCommentsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Cms_serviceDesc.Streams[0], c.cc, "/cms.Cms/GetPostComments", opts...)
	if err != nil {
		return nil, err
	}
	x := &cmsGetPostCommentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cms_GetPostCommentsClient interface {
	Recv() (*Comment, error)
	grpc.ClientStream
}

type cmsGetPostCommentsClient struct {
	grpc.ClientStream
}

func (x *cmsGetPostCommentsClient) Recv() (*Comment, error) {
	m := new(Comment)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cmsClient) GetPosts(ctx context.Context, in *GetPostsOptions, opts ...grpc.CallOption) (Cms_GetPostsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Cms_serviceDesc.Streams[1], c.cc, "/cms.Cms/GetPosts", opts...)
	if err != nil {
		return nil, err
	}
	x := &cmsGetPostsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cms_GetPostsClient interface {
	Recv() (*Post, error)
	grpc.ClientStream
}

type cmsGetPostsClient struct {
	grpc.ClientStream
}

func (x *cmsGetPostsClient) Recv() (*Post, error) {
	m := new(Post)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cmsClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserRequest, error) {
	out := new(UserRequest)
	err := grpc.Invoke(ctx, "/cms.Cms/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/cms.Cms/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) DeleteUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/cms.Cms/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) GetUserComments(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (Cms_GetUserCommentsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Cms_serviceDesc.Streams[2], c.cc, "/cms.Cms/GetUserComments", opts...)
	if err != nil {
		return nil, err
	}
	x := &cmsGetUserCommentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cms_GetUserCommentsClient interface {
	Recv() (*Comment, error)
	grpc.ClientStream
}

type cmsGetUserCommentsClient struct {
	grpc.ClientStream
}

func (x *cmsGetUserCommentsClient) Recv() (*Comment, error) {
	m := new(Comment)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cmsClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CommentRequest, error) {
	out := new(CommentRequest)
	err := grpc.Invoke(ctx, "/cms.Cms/CreateComment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) GetComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := grpc.Invoke(ctx, "/cms.Cms/GetComment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/cms.Cms/UpdateComment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) DeleteComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/cms.Cms/DeleteComment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) GetComments(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (Cms_GetCommentsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Cms_serviceDesc.Streams[3], c.cc, "/cms.Cms/GetComments", opts...)
	if err != nil {
		return nil, err
	}
	x := &cmsGetCommentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cms_GetCommentsClient interface {
	Recv() (*Comment, error)
	grpc.ClientStream
}

type cmsGetCommentsClient struct {
	grpc.ClientStream
}

func (x *cmsGetCommentsClient) Recv() (*Comment, error) {
	m := new(Comment)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cmsClient) AuthUser(ctx context.Context, in *AuthUserRequest, opts ...grpc.CallOption) (*AccessToken, error) {
	out := new(AccessToken)
	err := grpc.Invoke(ctx, "/cms.Cms/AuthUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cms service

type CmsServer interface {
	// Setup the application
	Setup(context.Context, *CreateUserRequest) (*UserRequest, error)
	// Check if application is setup
	IsSetup(context.Context, *google_protobuf1.Empty) (*google_protobuf2.BoolValue, error)
	// Create a post
	CreatePost(context.Context, *CreatePostRequest) (*PostRequest, error)
	// Get a post
	GetPost(context.Context, *PostRequest) (*Post, error)
	// Get a post (by slug)
	GetPostBySlug(context.Context, *PostBySlugRequest) (*Post, error)
	// Update a post
	UpdatePost(context.Context, *UpdatePostRequest) (*google_protobuf1.Empty, error)
	// Delete a post
	DeletePost(context.Context, *PostRequest) (*google_protobuf1.Empty, error)
	// Get all comments by post
	GetPostComments(*PostRequest, Cms_GetPostCommentsServer) error
	// Get all posts
	GetPosts(*GetPostsOptions, Cms_GetPostsServer) error
	// Create a user
	CreateUser(context.Context, *CreateUserRequest) (*UserRequest, error)
	// Get a user
	GetUser(context.Context, *UserRequest) (*User, error)
	// Delete a user
	DeleteUser(context.Context, *UserRequest) (*google_protobuf1.Empty, error)
	// Get all comments by user
	GetUserComments(*UserRequest, Cms_GetUserCommentsServer) error
	// Create a comment
	CreateComment(context.Context, *CreateCommentRequest) (*CommentRequest, error)
	// Get a comment
	GetComment(context.Context, *CommentRequest) (*Comment, error)
	// Update a comment
	UpdateComment(context.Context, *UpdateCommentRequest) (*google_protobuf1.Empty, error)
	// Delete a comment
	DeleteComment(context.Context, *CommentRequest) (*google_protobuf1.Empty, error)
	// Get all comments
	GetComments(*google_protobuf1.Empty, Cms_GetCommentsServer) error
	// Authorize as a user to get an access token
	AuthUser(context.Context, *AuthUserRequest) (*AccessToken, error)
}

func RegisterCmsServer(s *grpc.Server, srv CmsServer) {
	s.RegisterService(&_Cms_serviceDesc, srv)
}

func _Cms_Setup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).Setup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/Setup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).Setup(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_IsSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).IsSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/IsSetup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).IsSetup(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).GetPost(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_GetPostBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostBySlugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).GetPostBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/GetPostBySlug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).GetPostBySlug(ctx, req.(*PostBySlugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/UpdatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).UpdatePost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).DeletePost(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_GetPostComments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PostRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CmsServer).GetPostComments(m, &cmsGetPostCommentsServer{stream})
}

type Cms_GetPostCommentsServer interface {
	Send(*Comment) error
	grpc.ServerStream
}

type cmsGetPostCommentsServer struct {
	grpc.ServerStream
}

func (x *cmsGetPostCommentsServer) Send(m *Comment) error {
	return x.ServerStream.SendMsg(m)
}

func _Cms_GetPosts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPostsOptions)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CmsServer).GetPosts(m, &cmsGetPostsServer{stream})
}

type Cms_GetPostsServer interface {
	Send(*Post) error
	grpc.ServerStream
}

type cmsGetPostsServer struct {
	grpc.ServerStream
}

func (x *cmsGetPostsServer) Send(m *Post) error {
	return x.ServerStream.SendMsg(m)
}

func _Cms_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).DeleteUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_GetUserComments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CmsServer).GetUserComments(m, &cmsGetUserCommentsServer{stream})
}

type Cms_GetUserCommentsServer interface {
	Send(*Comment) error
	grpc.ServerStream
}

type cmsGetUserCommentsServer struct {
	grpc.ServerStream
}

func (x *cmsGetUserCommentsServer) Send(m *Comment) error {
	return x.ServerStream.SendMsg(m)
}

func _Cms_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_GetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).GetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/GetComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).GetComment(ctx, req.(*CommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/UpdateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).UpdateComment(ctx, req.(*UpdateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/DeleteComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).DeleteComment(ctx, req.(*CommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_GetComments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf1.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CmsServer).GetComments(m, &cmsGetCommentsServer{stream})
}

type Cms_GetCommentsServer interface {
	Send(*Comment) error
	grpc.ServerStream
}

type cmsGetCommentsServer struct {
	grpc.ServerStream
}

func (x *cmsGetCommentsServer) Send(m *Comment) error {
	return x.ServerStream.SendMsg(m)
}

func _Cms_AuthUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).AuthUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/AuthUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).AuthUser(ctx, req.(*AuthUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cms_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cms.Cms",
	HandlerType: (*CmsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Setup",
			Handler:    _Cms_Setup_Handler,
		},
		{
			MethodName: "IsSetup",
			Handler:    _Cms_IsSetup_Handler,
		},
		{
			MethodName: "CreatePost",
			Handler:    _Cms_CreatePost_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _Cms_GetPost_Handler,
		},
		{
			MethodName: "GetPostBySlug",
			Handler:    _Cms_GetPostBySlug_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _Cms_UpdatePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _Cms_DeletePost_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _Cms_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Cms_GetUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Cms_DeleteUser_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _Cms_CreateComment_Handler,
		},
		{
			MethodName: "GetComment",
			Handler:    _Cms_GetComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _Cms_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _Cms_DeleteComment_Handler,
		},
		{
			MethodName: "AuthUser",
			Handler:    _Cms_AuthUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPostComments",
			Handler:       _Cms_GetPostComments_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPosts",
			Handler:       _Cms_GetPosts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetUserComments",
			Handler:       _Cms_GetUserComments_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetComments",
			Handler:       _Cms_GetComments_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cms.proto",
}

func init() { proto.RegisterFile("cms.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1811 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0x6d, 0x4f, 0x23, 0xc9,
	0x11, 0x66, 0x8c, 0xf1, 0x4b, 0x79, 0x61, 0xd9, 0x5e, 0xb4, 0xe7, 0xf8, 0xf6, 0xd6, 0xb3, 0x73,
	0xdc, 0x69, 0x65, 0xe1, 0x17, 0x4c, 0x60, 0x59, 0x94, 0x0f, 0xb1, 0x59, 0xb2, 0x41, 0x49, 0xd8,
	0x95, 0x81, 0x5b, 0x6e, 0x11, 0x8b, 0xda, 0xe3, 0x3e, 0x7b, 0xee, 0xc6, 0x33, 0x93, 0xe9, 0x9e,
	0x03, 0x82, 0x90, 0x48, 0xa4, 0x93, 0xf2, 0xf2, 0x8d, 0x24, 0xdf, 0xf3, 0x1f, 0xf2, 0x03, 0xf2,
	0x1b, 0xa2, 0xfc, 0x00, 0x24, 0x2b, 0x3f, 0x24, 0xea, 0x9e, 0x57, 0xcf, 0xd8, 0xe4, 0x22, 0x25,
	0xda, 0x7c, 0x01, 0x77, 0x55, 0xf7, 0xd3, 0x55, 0xf5, 0x54, 0xd5, 0x54, 0x43, 0x5e, 0x1d, 0xd2,
	0x9a, 0x65, 0x9b, 0xcc, 0x44, 0xb3, 0xea, 0x90, 0x96, 0x1e, 0xf7, 0x4d, 0xb3, 0xaf, 0x93, 0x3a,
	0xb6, 0xb4, 0x3a, 0x36, 0x0c, 0x93, 0x61, 0xa6, 0x99, 0x86, 0xb7, 0xa5, 0xf4, 0xb1, 0xa7, 0x15,
	0xab, 0xae, 0xf3, 0x55, 0x9d, 0x0c, 0x2d, 0x76, 0xe1, 0x29, 0x9f, 0xc4, 0x95, 0x67, 0x36, 0xb6,
	0x2c, 0x62, 0xfb, 0x87, 0x37, 0xfa, 0x1a, 0x1b, 0x38, 0xdd, 0x9a, 0x6a, 0x0e, 0xeb, 0xc3, 0x33,
	0x8d, 0x7d, 0x63, 0x9e, 0xd5, 0xfb, 0x66, 0x55, 0x28, 0xab, 0xdf, 0x62, 0x5d, 0xeb, 0x61, 0x66,
	0xda, 0xb4, 0x1e, 0xfc, 0xf4, 0xce, 0xad, 0x88, 0x7f, 0x6a, 0xb5, 0x4f, 0x8c, 0x2a, 0x3d, 0xc3,
	0xfd, 0x3e, 0xb1, 0xeb, 0xa6, 0x25, 0xcc, 0x4a, 0x9a, 0xa8, 0xfc, 0x55, 0x82, 0xf4, 0x1b, 0x93,
	0x32, 0xb4, 0x00, 0x29, 0xad, 0x57, 0x94, 0x64, 0xe9, 0xd9, 0x7c, 0x27, 0xa5, 0xf5, 0xd0, 0x12,
	0xcc, 0x31, 0x8d, 0xe9, 0xa4, 0x98, 0x92, 0xa5, 0x67, 0xf9, 0x8e, 0xbb, 0x40, 0x45, 0xc8, 0xaa,
	0xa6, 0xc1, 0x88, 0xc1, 0x8a, 0xb3, 0x42, 0xee, 0x2f, 0x85, 0xc6, 0x26, 0x98, 0x91, 0x5e, 0x31,
	0xed, 0x69, 0xdc, 0x25, 0x2a, 0x43, 0x41, 0xc7, 0x94, 0x9d, 0x92, 0x9e, 0xc6, 0xb5, 0x73, 0x42,
	0x0b, 0x5c, 0xb4, 0x23, 0x24, 0xe8, 0x31, 0xe4, 0x2d, 0xa7, 0xab, 0x6b, 0x74, 0x40, 0x7a, 0xc5,
	0x8c, 0x2c, 0x3d, 0xcb, 0x75, 0x42, 0x01, 0x42, 0x90, 0xa6, 0xba, 0xd3, 0x2f, 0x66, 0xc5, 0x39,
	0xf1, 0x5b, 0xf9, 0x0c, 0x0a, 0xdc, 0xe8, 0x0e, 0xf9, 0xa5, 0x43, 0x28, 0x43, 0x8f, 0x42, 0xdb,
	0xdb, 0x99, 0xd1, 0x6d, 0x39, 0xb5, 0x38, 0xc3, 0x7d, 0x50, 0x56, 0xe1, 0x01, 0xdf, 0xd6, 0xbe,
	0xd8, 0xd7, 0x9d, 0xbe, 0xbf, 0xf9, 0xb1, 0x87, 0xc7, 0xb7, 0xe7, 0xdb, 0xb9, 0xd1, 0x6d, 0x39,
	0x7d, 0x24, 0x9d, 0x7f, 0xe6, 0x21, 0xb7, 0xe0, 0xfe, 0x2b, 0xc2, 0xf8, 0x29, 0xfa, 0xda, 0x0d,
	0x1a, 0xaa, 0x01, 0xd2, 0x0c, 0x55, 0x77, 0x7a, 0xe4, 0xd0, 0x78, 0x13, 0xd8, 0x99, 0x12, 0x76,
	0x4e, 0xd0, 0x28, 0xbf, 0x93, 0xe0, 0xc1, 0xb6, 0xf0, 0x3d, 0x6a, 0xe3, 0x6b, 0x3f, 0x9e, 0xee,
	0xbd, 0x2f, 0x46, 0xb7, 0xe5, 0x75, 0x80, 0xf7, 0xb5, 0xcb, 0xc6, 0x4a, 0x73, 0x7d, 0xe3, 0x6a,
	0xb9, 0xb2, 0x2c, 0xd4, 0xf2, 0xd0, 0xa1, 0x4c, 0xee, 0x12, 0xb9, 0xb9, 0xbe, 0x21, 0xab, 0x03,
	0x6c, 0x63, 0x95, 0x11, 0x9b, 0xca, 0xa6, 0x2d, 0xeb, 0x84, 0xd2, 0xf3, 0x5f, 0xa7, 0x7c, 0x2a,
	0x3e, 0x0d, 0xa9, 0x10, 0x14, 0xb5, 0xf3, 0xa3, 0xdb, 0xf2, 0xdc, 0xf9, 0xf5, 0xf5, 0x75, 0x2e,
	0x60, 0x45, 0x39, 0x00, 0x14, 0x9a, 0xf2, 0x56, 0x63, 0x03, 0x1e, 0x09, 0x54, 0x81, 0xb4, 0x65,
	0x52, 0x26, 0x4c, 0x29, 0x34, 0x1f, 0xd5, 0x78, 0x52, 0x27, 0x2c, 0xee, 0x88, 0x3d, 0x41, 0xf8,
	0x53, 0x91, 0xf0, 0xff, 0x4d, 0x82, 0x07, 0x87, 0x56, 0x2f, 0xe6, 0xe1, 0x14, 0x16, 0x42, 0xcf,
	0x53, 0xff, 0x7d, 0xcf, 0x67, 0xa7, 0x79, 0x3e, 0x9e, 0x54, 0xe9, 0x58, 0x52, 0xf1, 0xb8, 0x84,
	0x0e, 0xdc, 0x19, 0x97, 0x84, 0x9f, 0x77, 0xc4, 0xe5, 0x2f, 0x12, 0x64, 0xb7, 0xcd, 0xe1, 0x90,
	0xdf, 0x1f, 0xaf, 0xa7, 0x62, 0x8c, 0xae, 0x89, 0x95, 0x33, 0x7b, 0x67, 0xe5, 0xa4, 0x13, 0x95,
	0xf3, 0x11, 0x64, 0x1d, 0x4a, 0xec, 0x53, 0xcd, 0x2f, 0xab, 0x0c, 0x5f, 0xee, 0x0a, 0x05, 0xb7,
	0x92, 0x2b, 0x32, 0xae, 0x82, 0x2f, 0x77, 0x7b, 0xca, 0x33, 0x58, 0xf0, 0x2c, 0xfc, 0x77, 0xc5,
	0xf3, 0x77, 0x09, 0x96, 0xdc, 0xa4, 0x88, 0x1d, 0x58, 0x0e, 0x3d, 0x71, 0x73, 0x19, 0x46, 0xb7,
	0xe5, 0xcc, 0x91, 0x74, 0x7e, 0x7d, 0x9d, 0x0e, 0xbd, 0xb2, 0x43, 0xd3, 0x5c, 0xde, 0xbf, 0x1c,
	0xdd, 0x96, 0x0f, 0xe1, 0xe1, 0xfb, 0xe3, 0xe3, 0x2d, 0xac, 0x5b, 0x03, 0xbc, 0x75, 0x72, 0x72,
	0xb9, 0xb6, 0xb2, 0xba, 0x79, 0xb5, 0x5c, 0xf9, 0xd1, 0x21, 0x25, 0xb6, 0xbc, 0xdb, 0x0b, 0x52,
	0x60, 0xad, 0xba, 0xba, 0x19, 0xcd, 0x01, 0x6c, 0xf4, 0x64, 0x15, 0x1b, 0xb2, 0x69, 0xe8, 0x17,
	0xb2, 0x57, 0x72, 0xb2, 0x4e, 0x18, 0x57, 0x1e, 0x49, 0x81, 0xd7, 0xe5, 0xd0, 0xeb, 0xd9, 0x31,
	0x7f, 0x7c, 0xef, 0x0f, 0x60, 0xc9, 0xe5, 0xf3, 0xfb, 0xc5, 0x20, 0xea, 0x6a, 0x6a, 0xaa, 0xab,
	0xca, 0xef, 0x25, 0x48, 0x73, 0x0f, 0x22, 0x9c, 0xe7, 0xfd, 0x1e, 0x4a, 0x86, 0x58, 0xd3, 0xfd,
	0x1e, 0x2a, 0x16, 0xdf, 0x83, 0x6f, 0xac, 0x32, 0xed, 0x5b, 0x12, 0xe5, 0xbb, 0x25, 0x24, 0xe8,
	0x29, 0xa4, 0x6d, 0x53, 0x27, 0x82, 0xec, 0x85, 0xe6, 0xbc, 0x9b, 0xa0, 0x94, 0xd8, 0x1d, 0x53,
	0x27, 0x1d, 0xa1, 0x52, 0xce, 0xa1, 0x20, 0x24, 0x9e, 0x67, 0x5a, 0x68, 0xd2, 0xff, 0x92, 0x01,
	0x9e, 0x30, 0xdf, 0xcd, 0xfa, 0x7d, 0xef, 0xc3, 0x18, 0x80, 0x86, 0x63, 0xe1, 0x6e, 0xbf, 0x1d,
	0xdd, 0x96, 0xf7, 0xe1, 0xb9, 0x7b, 0x9b, 0xe1, 0x0c, 0xb7, 0x4e, 0x4e, 0x8e, 0xab, 0xa7, 0x35,
	0x5c, 0xfd, 0x55, 0xab, 0xfa, 0xae, 0x51, 0x7d, 0x71, 0x72, 0xd9, 0x58, 0xd9, 0x58, 0xbb, 0xfa,
	0x71, 0x4c, 0xb8, 0xba, 0xb2, 0xfa, 0xa2, 0x71, 0xb5, 0x5c, 0x79, 0xb8, 0xc3, 0xb1, 0x02, 0x7b,
	0xc4, 0x67, 0x96, 0x33, 0x9f, 0xf2, 0x79, 0xfc, 0xb3, 0x04, 0x39, 0x0b, 0x53, 0x7a, 0x66, 0xda,
	0x1e, 0x93, 0xed, 0x8b, 0xd1, 0x6d, 0xd9, 0x71, 0x1d, 0xec, 0xdb, 0xd8, 0x1a, 0x70, 0x07, 0x37,
	0x56, 0xd6, 0x39, 0xdc, 0xbb, 0x37, 0xde, 0xd6, 0x00, 0x11, 0x33, 0x59, 0x27, 0x98, 0x32, 0x79,
	0x43, 0xb6, 0x6c, 0xcd, 0x60, 0xb8, 0xab, 0x93, 0xa8, 0xc7, 0x67, 0x1a, 0x1b, 0x98, 0x0e, 0x93,
	0xcf, 0x06, 0x1a, 0x23, 0xd4, 0xc2, 0x2a, 0x11, 0xcd, 0x90, 0x67, 0x9d, 0x6d, 0xea, 0x91, 0x9d,
	0x47, 0xd2, 0xf9, 0x5a, 0x27, 0x30, 0x45, 0x51, 0xfd, 0x9e, 0xcf, 0x43, 0xca, 0x7b, 0x1b, 0xcf,
	0x0e, 0xde, 0xdb, 0x78, 0x95, 0x4c, 0xe8, 0xf9, 0x11, 0xb6, 0x3a, 0x62, 0x4f, 0x90, 0x66, 0xa9,
	0xe9, 0x69, 0xf6, 0xa7, 0x14, 0xdc, 0x6f, 0x39, 0x6c, 0xf0, 0x81, 0xa8, 0x1e, 0x8b, 0x7d, 0xea,
	0xff, 0x27, 0xf6, 0x06, 0x14, 0x5a, 0xaa, 0x4a, 0x28, 0x3d, 0x30, 0xbf, 0x21, 0x06, 0x7a, 0x0a,
	0xf7, 0xb0, 0x58, 0x9e, 0x32, 0xbe, 0xf6, 0x5a, 0x43, 0x01, 0x47, 0xb6, 0x7c, 0x02, 0x20, 0x74,
	0xa7, 0xec, 0xc2, 0xf2, 0x87, 0xad, 0xbc, 0x90, 0x1c, 0x5c, 0x58, 0x84, 0xab, 0xc9, 0xb9, 0xa5,
	0xd9, 0x84, 0x9e, 0x6a, 0x86, 0xdb, 0xd5, 0x3a, 0x79, 0x4f, 0xb2, 0x6b, 0x28, 0x4d, 0x80, 0x7d,
	0x66, 0xb7, 0x8c, 0xde, 0x4f, 0x31, 0x1d, 0xa0, 0x45, 0x98, 0xa5, 0xcc, 0xf6, 0x6e, 0xe1, 0x3f,
	0xf9, 0x57, 0x6a, 0x80, 0xe9, 0xc0, 0xff, 0x4a, 0xf1, 0xdf, 0xca, 0x97, 0x30, 0x27, 0x52, 0x9b,
	0xb7, 0x2b, 0x66, 0xfa, 0xed, 0x8a, 0x99, 0x7c, 0xf3, 0x57, 0xb6, 0x39, 0xf4, 0x37, 0xf3, 0xdf,
	0xbc, 0x59, 0x51, 0xa7, 0xfb, 0x35, 0x51, 0x83, 0x81, 0xcf, 0x5b, 0xf2, 0xdd, 0x5d, 0xb3, 0x77,
	0xe1, 0x75, 0x29, 0xf1, 0x5b, 0xa9, 0xc0, 0x3d, 0x4e, 0xae, 0x1f, 0x6e, 0x54, 0x8a, 0xb0, 0xe4,
	0xde, 0x13, 0xac, 0x2b, 0x2b, 0x90, 0xf3, 0x73, 0x0a, 0x15, 0x20, 0x7b, 0xb8, 0xf7, 0xb3, 0xbd,
	0xd7, 0x6f, 0xf7, 0x16, 0x67, 0x50, 0x1e, 0xe6, 0x5a, 0x2f, 0x7f, 0xb1, 0xbb, 0xb7, 0x28, 0xa1,
	0x1c, 0xa4, 0x0f, 0xf7, 0x77, 0x3a, 0x8b, 0xa9, 0xe6, 0x77, 0x12, 0x64, 0xb8, 0x8f, 0xc4, 0x46,
	0x2f, 0x21, 0x2d, 0xbc, 0x7d, 0x5c, 0x73, 0x27, 0xe8, 0x9a, 0x3f, 0x41, 0xd7, 0xf6, 0x99, 0xad,
	0x19, 0xfd, 0x2f, 0xb0, 0xee, 0x90, 0xd2, 0x9d, 0x5a, 0x65, 0x06, 0xad, 0x43, 0xee, 0x0b, 0x77,
	0x72, 0x26, 0xe8, 0xbe, 0xc8, 0xf0, 0x30, 0x90, 0xa5, 0x47, 0x89, 0xc3, 0x3b, 0x7c, 0x72, 0x57,
	0x66, 0x9a, 0xcf, 0x21, 0x2b, 0x82, 0x47, 0x6c, 0xb4, 0x02, 0xe9, 0x7d, 0x62, 0xf4, 0x10, 0x88,
	0xd3, 0x42, 0x7a, 0xc7, 0xc1, 0x3f, 0x48, 0x50, 0xd8, 0x1e, 0xd2, 0x5d, 0x83, 0x11, 0xdb, 0xc0,
	0x3a, 0xda, 0x14, 0x83, 0xe6, 0x58, 0xb4, 0x16, 0xc3, 0x42, 0x73, 0x2b, 0xaa, 0xf4, 0x20, 0x90,
	0xf8, 0x9b, 0x94, 0x19, 0xd4, 0xf6, 0x3f, 0x62, 0x5c, 0xfe, 0xf3, 0xf0, 0xe3, 0x90, 0x3c, 0x3e,
	0xdd, 0x9a, 0x6d, 0xc8, 0x6e, 0x0f, 0x29, 0x2f, 0x60, 0xb4, 0x09, 0x1f, 0x09, 0x00, 0xcc, 0xc8,
	0x1e, 0x39, 0x13, 0x49, 0xf9, 0x13, 0xd3, 0x16, 0xdf, 0xb3, 0x7c, 0x80, 0x58, 0x72, 0xc1, 0x23,
	0xb9, 0xad, 0xcc, 0x34, 0x7f, 0x3b, 0x0f, 0xb3, 0xdb, 0x43, 0x8a, 0xf6, 0x60, 0x6e, 0x9f, 0x30,
	0xc7, 0x42, 0x53, 0xba, 0x4a, 0x29, 0x61, 0x99, 0xf2, 0xf1, 0x4d, 0x2b, 0xeb, 0x9d, 0xfa, 0xcd,
	0x3f, 0xfe, 0xf9, 0xc7, 0x54, 0x41, 0xc9, 0xd4, 0x29, 0x5f, 0x6d, 0x49, 0x15, 0xf4, 0x0e, 0xb2,
	0xbb, 0xd4, 0x47, 0x9c, 0xe8, 0x41, 0xa9, 0x94, 0x90, 0xb7, 0x4d, 0x53, 0x77, 0xb9, 0x4d, 0x60,
	0xa3, 0x7c, 0x5d, 0xa3, 0x55, 0x01, 0x8f, 0xf6, 0x01, 0xc2, 0x49, 0x17, 0x4d, 0x19, 0x7d, 0x3d,
	0x83, 0x23, 0x12, 0x0f, 0x54, 0xbc, 0x0b, 0x02, 0x83, 0xf9, 0x50, 0x41, 0xb9, 0xc1, 0x3b, 0x90,
	0xf5, 0x1e, 0x0d, 0x28, 0x71, 0xb2, 0x94, 0x0f, 0x24, 0xca, 0x27, 0x31, 0x90, 0x79, 0x54, 0x70,
	0x41, 0xea, 0x97, 0x5a, 0xef, 0x0a, 0x1d, 0xc1, 0xbc, 0x07, 0xe3, 0xbe, 0x58, 0x3c, 0xf3, 0x12,
	0x4f, 0x98, 0x28, 0xe4, 0x72, 0x0c, 0x72, 0x09, 0x21, 0x0f, 0x92, 0x4f, 0xa4, 0xf5, 0x4b, 0xfe,
	0xf7, 0x0a, 0xbd, 0x07, 0x08, 0xe7, 0x58, 0x34, 0x65, 0xb0, 0x9d, 0x9a, 0x2e, 0x72, 0xec, 0x8e,
	0xc5, 0x52, 0xd4, 0x6c, 0x1e, 0x80, 0x43, 0x80, 0x97, 0x44, 0x27, 0x1e, 0x7e, 0x32, 0x06, 0xd3,
	0x90, 0x13, 0x01, 0xa9, 0x8c, 0x05, 0xe4, 0x38, 0x78, 0x8c, 0x79, 0xf3, 0x1a, 0x9d, 0x80, 0x7d,
	0xcf, 0xe5, 0xd0, 0xdd, 0xa0, 0x7c, 0x1e, 0x43, 0x7c, 0x84, 0x96, 0x22, 0x88, 0x75, 0xd5, 0xc3,
	0x69, 0x48, 0xe8, 0x15, 0xe4, 0xfc, 0x97, 0x1e, 0x5a, 0x12, 0x18, 0xb1, 0x87, 0x5f, 0x34, 0xcc,
	0xc5, 0x18, 0x6c, 0x0e, 0x79, 0xf4, 0x37, 0xa4, 0x30, 0xa5, 0x44, 0xcd, 0xfc, 0xa7, 0x35, 0xc0,
	0x25, 0x61, 0x4a, 0xf1, 0xcf, 0x6f, 0x24, 0xa5, 0x04, 0x62, 0xb2, 0xae, 0xc3, 0xba, 0xf4, 0x22,
	0x18, 0x82, 0xf0, 0x94, 0x12, 0x20, 0x6e, 0x04, 0x03, 0x62, 0xa6, 0x20, 0xdd, 0x4d, 0x4c, 0x04,
	0xb6, 0x32, 0x06, 0x7b, 0x1c, 0x34, 0xaf, 0x18, 0x31, 0x51, 0xec, 0x49, 0xc4, 0x84, 0x88, 0x9c,
	0x98, 0x10, 0x31, 0x4a, 0x4c, 0x17, 0xe6, 0xc7, 0xde, 0x1d, 0xe8, 0x07, 0x91, 0x90, 0x8e, 0x0f,
	0xee, 0xa5, 0x87, 0xd1, 0x3b, 0xfc, 0xc0, 0x3e, 0xbd, 0x69, 0x01, 0xe4, 0x7c, 0xcb, 0xc4, 0x6d,
	0x0b, 0x4a, 0x3e, 0xb8, 0x82, 0x87, 0xf7, 0x00, 0xe0, 0x15, 0xf1, 0xb3, 0x0a, 0x4d, 0x42, 0x89,
	0x99, 0xff, 0x69, 0x12, 0x73, 0x11, 0x2d, 0x04, 0x98, 0x6e, 0x58, 0xbe, 0x86, 0xf9, 0xb1, 0xe7,
	0x85, 0x67, 0xf9, 0xa4, 0x27, 0xc7, 0xd4, 0xc8, 0x7f, 0x9e, 0xbc, 0xe8, 0x61, 0x29, 0x76, 0x11,
	0xf7, 0x00, 0xc3, 0xbc, 0xcb, 0xec, 0x9d, 0x4e, 0x4c, 0xbb, 0x65, 0x92, 0x3b, 0x95, 0xb8, 0x3b,
	0x87, 0x50, 0x08, 0x83, 0x44, 0xa7, 0xf6, 0xe2, 0xf1, 0x40, 0x3d, 0x49, 0x22, 0xf3, 0x06, 0x1c,
	0xe1, 0xb7, 0x03, 0x39, 0x7f, 0x72, 0xf4, 0x0a, 0x2f, 0x36, 0x48, 0x4e, 0xf8, 0xd8, 0x3c, 0xb9,
	0x69, 0x65, 0x20, 0xcd, 0xf7, 0x09, 0xc4, 0xfb, 0x0a, 0xd4, 0xb1, 0xc3, 0x06, 0x22, 0x83, 0xb6,
	0xa4, 0x4a, 0xfb, 0xf9, 0x4d, 0xeb, 0x87, 0x28, 0xdb, 0x9c, 0x5b, 0xad, 0x35, 0x6a, 0x8d, 0x12,
	0x9f, 0xed, 0x6c, 0x83, 0xf4, 0xaa, 0x94, 0x99, 0x06, 0xa9, 0xae, 0x6e, 0xbe, 0xd8, 0x6c, 0x34,
	0x6b, 0xd8, 0xb2, 0xa8, 0x65, 0xb2, 0x9a, 0x6a, 0x0e, 0x95, 0x74, 0x1d, 0x5b, 0x5a, 0x45, 0x4a,
	0x75, 0x33, 0xc2, 0x99, 0xb5, 0x7f, 0x05, 0x00, 0x00, 0xff, 0xff, 0x37, 0xd6, 0xe0, 0x26, 0xd9,
	0x13, 0x00, 0x00,
}
