// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cms.proto

/*
Package cms is a generated protocol buffer package.

CMS

CMS Service API provides access to CMS entities and supports CMS use-cases

It is generated from these files:
	cms.proto

It has these top-level messages:
	Post
	PostRequest
	CreatePostRequest
	UpdatePostRequest
	Comment
	CommentRequest
	CreateCommentRequest
	UpdateCommentRequest
	User
	UserRequest
	CreateUserRequest
	CreateUserWithRole
	AuthUserRequest
	AccessToken
	UserPassword
*/
package cms

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"
import google_protobuf2 "github.com/golang/protobuf/ptypes/wrappers"
import _ "github.com/mwitkow/go-proto-validators"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Users
type UserRole int32

const (
	UserRole_UNKNOWN UserRole = 0
	UserRole_ADMIN   UserRole = 1
	UserRole_USER    UserRole = 2
)

var UserRole_name = map[int32]string{
	0: "UNKNOWN",
	1: "ADMIN",
	2: "USER",
}
var UserRole_value = map[string]int32{
	"UNKNOWN": 0,
	"ADMIN":   1,
	"USER":    2,
}

func (x UserRole) String() string {
	return proto.EnumName(UserRole_name, int32(x))
}
func (UserRole) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Posts
type Post struct {
	Id         uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title      string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Content    string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	Created    string `protobuf:"bytes,4,opt,name=created" json:"created,omitempty"`
	LastEdited string `protobuf:"bytes,5,opt,name=last_edited,json=lastEdited" json:"last_edited,omitempty"`
	Published  string `protobuf:"bytes,6,opt,name=published" json:"published,omitempty"`
	Slug       string `protobuf:"bytes,7,opt,name=slug" json:"slug,omitempty"`
}

func (m *Post) Reset()                    { *m = Post{} }
func (m *Post) String() string            { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()               {}
func (*Post) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Post) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Post) GetLastEdited() string {
	if m != nil {
		return m.LastEdited
	}
	return ""
}

func (m *Post) GetPublished() string {
	if m != nil {
		return m.Published
	}
	return ""
}

func (m *Post) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type PostRequest struct {
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *PostRequest) Reset()                    { *m = PostRequest{} }
func (m *PostRequest) String() string            { return proto.CompactTextString(m) }
func (*PostRequest) ProtoMessage()               {}
func (*PostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PostRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreatePostRequest struct {
	Title   string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	Slug    string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty"`
}

func (m *CreatePostRequest) Reset()                    { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()               {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreatePostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreatePostRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type UpdatePostRequest struct {
	Id      uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
	Slug    string `protobuf:"bytes,4,opt,name=slug" json:"slug,omitempty"`
}

func (m *UpdatePostRequest) Reset()                    { *m = UpdatePostRequest{} }
func (m *UpdatePostRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatePostRequest) ProtoMessage()               {}
func (*UpdatePostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpdatePostRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdatePostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *UpdatePostRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

// Comments
type Comment struct {
	Id         uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Content    string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
	Created    string `protobuf:"bytes,3,opt,name=created" json:"created,omitempty"`
	LastEdited string `protobuf:"bytes,4,opt,name=last_edited,json=lastEdited" json:"last_edited,omitempty"`
	UserId     string `protobuf:"bytes,5,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	PostId     string `protobuf:"bytes,6,opt,name=post_id,json=postId" json:"post_id,omitempty"`
}

func (m *Comment) Reset()                    { *m = Comment{} }
func (m *Comment) String() string            { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()               {}
func (*Comment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Comment) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Comment) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Comment) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *Comment) GetLastEdited() string {
	if m != nil {
		return m.LastEdited
	}
	return ""
}

func (m *Comment) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Comment) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

type CommentRequest struct {
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *CommentRequest) Reset()                    { *m = CommentRequest{} }
func (m *CommentRequest) String() string            { return proto.CompactTextString(m) }
func (*CommentRequest) ProtoMessage()               {}
func (*CommentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CommentRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateCommentRequest struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	UserId  string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	PostId  uint32 `protobuf:"varint,3,opt,name=post_id,json=postId" json:"post_id,omitempty"`
}

func (m *CreateCommentRequest) Reset()                    { *m = CreateCommentRequest{} }
func (m *CreateCommentRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCommentRequest) ProtoMessage()               {}
func (*CreateCommentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CreateCommentRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreateCommentRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateCommentRequest) GetPostId() uint32 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type UpdateCommentRequest struct {
	Id      uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Content string `protobuf:"bytes,2,opt,name=content" json:"content,omitempty"`
}

func (m *UpdateCommentRequest) Reset()                    { *m = UpdateCommentRequest{} }
func (m *UpdateCommentRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateCommentRequest) ProtoMessage()               {}
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateCommentRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateCommentRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type User struct {
	Id         string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Email      string   `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Created    string   `protobuf:"bytes,3,opt,name=created" json:"created,omitempty"`
	LastActive string   `protobuf:"bytes,4,opt,name=last_active,json=lastActive" json:"last_active,omitempty"`
	Role       UserRole `protobuf:"varint,5,opt,name=role,enum=cms.UserRole" json:"role,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *User) GetLastActive() string {
	if m != nil {
		return m.LastActive
	}
	return ""
}

func (m *User) GetRole() UserRole {
	if m != nil {
		return m.Role
	}
	return UserRole_UNKNOWN
}

type UserRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *UserRequest) Reset()                    { *m = UserRequest{} }
func (m *UserRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()               {}
func (*UserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateUserRequest struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *CreateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserWithRole struct {
	User *CreateUserRequest `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Role UserRole           `protobuf:"varint,2,opt,name=role,enum=cms.UserRole" json:"role,omitempty"`
}

func (m *CreateUserWithRole) Reset()                    { *m = CreateUserWithRole{} }
func (m *CreateUserWithRole) String() string            { return proto.CompactTextString(m) }
func (*CreateUserWithRole) ProtoMessage()               {}
func (*CreateUserWithRole) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *CreateUserWithRole) GetUser() *CreateUserRequest {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateUserWithRole) GetRole() UserRole {
	if m != nil {
		return m.Role
	}
	return UserRole_UNKNOWN
}

type AuthUserRequest struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *AuthUserRequest) Reset()                    { *m = AuthUserRequest{} }
func (m *AuthUserRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthUserRequest) ProtoMessage()               {}
func (*AuthUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *AuthUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AuthUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AccessToken struct {
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	TokenType   string `protobuf:"bytes,2,opt,name=token_type,json=tokenType" json:"token_type,omitempty"`
	ExpiresIn   uint32 `protobuf:"varint,3,opt,name=expires_in,json=expiresIn" json:"expires_in,omitempty"`
}

func (m *AccessToken) Reset()                    { *m = AccessToken{} }
func (m *AccessToken) String() string            { return proto.CompactTextString(m) }
func (*AccessToken) ProtoMessage()               {}
func (*AccessToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *AccessToken) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *AccessToken) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *AccessToken) GetExpiresIn() uint32 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

type UserPassword struct {
	Password string `protobuf:"bytes,1,opt,name=password" json:"password,omitempty"`
}

func (m *UserPassword) Reset()                    { *m = UserPassword{} }
func (m *UserPassword) String() string            { return proto.CompactTextString(m) }
func (*UserPassword) ProtoMessage()               {}
func (*UserPassword) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *UserPassword) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*Post)(nil), "cms.Post")
	proto.RegisterType((*PostRequest)(nil), "cms.PostRequest")
	proto.RegisterType((*CreatePostRequest)(nil), "cms.CreatePostRequest")
	proto.RegisterType((*UpdatePostRequest)(nil), "cms.UpdatePostRequest")
	proto.RegisterType((*Comment)(nil), "cms.Comment")
	proto.RegisterType((*CommentRequest)(nil), "cms.CommentRequest")
	proto.RegisterType((*CreateCommentRequest)(nil), "cms.CreateCommentRequest")
	proto.RegisterType((*UpdateCommentRequest)(nil), "cms.UpdateCommentRequest")
	proto.RegisterType((*User)(nil), "cms.User")
	proto.RegisterType((*UserRequest)(nil), "cms.UserRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "cms.CreateUserRequest")
	proto.RegisterType((*CreateUserWithRole)(nil), "cms.CreateUserWithRole")
	proto.RegisterType((*AuthUserRequest)(nil), "cms.AuthUserRequest")
	proto.RegisterType((*AccessToken)(nil), "cms.AccessToken")
	proto.RegisterType((*UserPassword)(nil), "cms.UserPassword")
	proto.RegisterEnum("cms.UserRole", UserRole_name, UserRole_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CmsInternal service

type CmsInternalClient interface {
	GetUserPassword(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserPassword, error)
}

type cmsInternalClient struct {
	cc *grpc.ClientConn
}

func NewCmsInternalClient(cc *grpc.ClientConn) CmsInternalClient {
	return &cmsInternalClient{cc}
}

func (c *cmsInternalClient) GetUserPassword(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserPassword, error) {
	out := new(UserPassword)
	err := grpc.Invoke(ctx, "/cms.CmsInternal/GetUserPassword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CmsInternal service

type CmsInternalServer interface {
	GetUserPassword(context.Context, *UserRequest) (*UserPassword, error)
}

func RegisterCmsInternalServer(s *grpc.Server, srv CmsInternalServer) {
	s.RegisterService(&_CmsInternal_serviceDesc, srv)
}

func _CmsInternal_GetUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsInternalServer).GetUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.CmsInternal/GetUserPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsInternalServer).GetUserPassword(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CmsInternal_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cms.CmsInternal",
	HandlerType: (*CmsInternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserPassword",
			Handler:    _CmsInternal_GetUserPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cms.proto",
}

// Client API for CmsAuth service

type CmsAuthClient interface {
	ActivateNewTokenForUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*AccessToken, error)
}

type cmsAuthClient struct {
	cc *grpc.ClientConn
}

func NewCmsAuthClient(cc *grpc.ClientConn) CmsAuthClient {
	return &cmsAuthClient{cc}
}

func (c *cmsAuthClient) ActivateNewTokenForUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*AccessToken, error) {
	out := new(AccessToken)
	err := grpc.Invoke(ctx, "/cms.CmsAuth/ActivateNewTokenForUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CmsAuth service

type CmsAuthServer interface {
	ActivateNewTokenForUser(context.Context, *User) (*AccessToken, error)
}

func RegisterCmsAuthServer(s *grpc.Server, srv CmsAuthServer) {
	s.RegisterService(&_CmsAuth_serviceDesc, srv)
}

func _CmsAuth_ActivateNewTokenForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsAuthServer).ActivateNewTokenForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.CmsAuth/ActivateNewTokenForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsAuthServer).ActivateNewTokenForUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _CmsAuth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cms.CmsAuth",
	HandlerType: (*CmsAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ActivateNewTokenForUser",
			Handler:    _CmsAuth_ActivateNewTokenForUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cms.proto",
}

// Client API for Cms service

type CmsClient interface {
	// Setup the application
	Setup(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserRequest, error)
	// Check if application is setup
	IsSetup(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf2.BoolValue, error)
	// Create a post
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*PostRequest, error)
	// Get a post
	GetPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*Post, error)
	// Update a post
	UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Delete a post
	DeletePost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Get all comments by post
	GetPostComments(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (Cms_GetPostCommentsClient, error)
	// Get all posts
	GetPosts(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (Cms_GetPostsClient, error)
	// Publish a post
	PublishPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// UnPublish a post
	UnPublishPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Create a user
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserRequest, error)
	// Get a user
	GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error)
	// Delete a user
	DeleteUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Get all comments by user
	GetUserComments(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (Cms_GetUserCommentsClient, error)
	// Create a comment
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CommentRequest, error)
	// Get a comment
	GetComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*Comment, error)
	// Update a comment
	UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Delete a comment
	DeleteComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	// Get all comments
	GetComments(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (Cms_GetCommentsClient, error)
	// Authorize as a user to get an access token
	AuthUser(ctx context.Context, in *AuthUserRequest, opts ...grpc.CallOption) (*AccessToken, error)
}

type cmsClient struct {
	cc *grpc.ClientConn
}

func NewCmsClient(cc *grpc.ClientConn) CmsClient {
	return &cmsClient{cc}
}

func (c *cmsClient) Setup(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserRequest, error) {
	out := new(UserRequest)
	err := grpc.Invoke(ctx, "/cms.Cms/Setup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) IsSetup(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf2.BoolValue, error) {
	out := new(google_protobuf2.BoolValue)
	err := grpc.Invoke(ctx, "/cms.Cms/IsSetup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*PostRequest, error) {
	out := new(PostRequest)
	err := grpc.Invoke(ctx, "/cms.Cms/CreatePost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) GetPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := grpc.Invoke(ctx, "/cms.Cms/GetPost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) UpdatePost(ctx context.Context, in *UpdatePostRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/cms.Cms/UpdatePost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) DeletePost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/cms.Cms/DeletePost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) GetPostComments(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (Cms_GetPostCommentsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Cms_serviceDesc.Streams[0], c.cc, "/cms.Cms/GetPostComments", opts...)
	if err != nil {
		return nil, err
	}
	x := &cmsGetPostCommentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cms_GetPostCommentsClient interface {
	Recv() (*Comment, error)
	grpc.ClientStream
}

type cmsGetPostCommentsClient struct {
	grpc.ClientStream
}

func (x *cmsGetPostCommentsClient) Recv() (*Comment, error) {
	m := new(Comment)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cmsClient) GetPosts(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (Cms_GetPostsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Cms_serviceDesc.Streams[1], c.cc, "/cms.Cms/GetPosts", opts...)
	if err != nil {
		return nil, err
	}
	x := &cmsGetPostsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cms_GetPostsClient interface {
	Recv() (*Post, error)
	grpc.ClientStream
}

type cmsGetPostsClient struct {
	grpc.ClientStream
}

func (x *cmsGetPostsClient) Recv() (*Post, error) {
	m := new(Post)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cmsClient) PublishPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/cms.Cms/PublishPost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) UnPublishPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/cms.Cms/UnPublishPost", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*UserRequest, error) {
	out := new(UserRequest)
	err := grpc.Invoke(ctx, "/cms.Cms/CreateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/cms.Cms/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) DeleteUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/cms.Cms/DeleteUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) GetUserComments(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (Cms_GetUserCommentsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Cms_serviceDesc.Streams[2], c.cc, "/cms.Cms/GetUserComments", opts...)
	if err != nil {
		return nil, err
	}
	x := &cmsGetUserCommentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cms_GetUserCommentsClient interface {
	Recv() (*Comment, error)
	grpc.ClientStream
}

type cmsGetUserCommentsClient struct {
	grpc.ClientStream
}

func (x *cmsGetUserCommentsClient) Recv() (*Comment, error) {
	m := new(Comment)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cmsClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CommentRequest, error) {
	out := new(CommentRequest)
	err := grpc.Invoke(ctx, "/cms.Cms/CreateComment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) GetComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := grpc.Invoke(ctx, "/cms.Cms/GetComment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/cms.Cms/UpdateComment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) DeleteComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/cms.Cms/DeleteComment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmsClient) GetComments(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (Cms_GetCommentsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Cms_serviceDesc.Streams[3], c.cc, "/cms.Cms/GetComments", opts...)
	if err != nil {
		return nil, err
	}
	x := &cmsGetCommentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cms_GetCommentsClient interface {
	Recv() (*Comment, error)
	grpc.ClientStream
}

type cmsGetCommentsClient struct {
	grpc.ClientStream
}

func (x *cmsGetCommentsClient) Recv() (*Comment, error) {
	m := new(Comment)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cmsClient) AuthUser(ctx context.Context, in *AuthUserRequest, opts ...grpc.CallOption) (*AccessToken, error) {
	out := new(AccessToken)
	err := grpc.Invoke(ctx, "/cms.Cms/AuthUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cms service

type CmsServer interface {
	// Setup the application
	Setup(context.Context, *CreateUserRequest) (*UserRequest, error)
	// Check if application is setup
	IsSetup(context.Context, *google_protobuf1.Empty) (*google_protobuf2.BoolValue, error)
	// Create a post
	CreatePost(context.Context, *CreatePostRequest) (*PostRequest, error)
	// Get a post
	GetPost(context.Context, *PostRequest) (*Post, error)
	// Update a post
	UpdatePost(context.Context, *UpdatePostRequest) (*google_protobuf1.Empty, error)
	// Delete a post
	DeletePost(context.Context, *PostRequest) (*google_protobuf1.Empty, error)
	// Get all comments by post
	GetPostComments(*PostRequest, Cms_GetPostCommentsServer) error
	// Get all posts
	GetPosts(*google_protobuf1.Empty, Cms_GetPostsServer) error
	// Publish a post
	PublishPost(context.Context, *PostRequest) (*google_protobuf1.Empty, error)
	// UnPublish a post
	UnPublishPost(context.Context, *PostRequest) (*google_protobuf1.Empty, error)
	// Create a user
	CreateUser(context.Context, *CreateUserRequest) (*UserRequest, error)
	// Get a user
	GetUser(context.Context, *UserRequest) (*User, error)
	// Delete a user
	DeleteUser(context.Context, *UserRequest) (*google_protobuf1.Empty, error)
	// Get all comments by user
	GetUserComments(*UserRequest, Cms_GetUserCommentsServer) error
	// Create a comment
	CreateComment(context.Context, *CreateCommentRequest) (*CommentRequest, error)
	// Get a comment
	GetComment(context.Context, *CommentRequest) (*Comment, error)
	// Update a comment
	UpdateComment(context.Context, *UpdateCommentRequest) (*google_protobuf1.Empty, error)
	// Delete a comment
	DeleteComment(context.Context, *CommentRequest) (*google_protobuf1.Empty, error)
	// Get all comments
	GetComments(*google_protobuf1.Empty, Cms_GetCommentsServer) error
	// Authorize as a user to get an access token
	AuthUser(context.Context, *AuthUserRequest) (*AccessToken, error)
}

func RegisterCmsServer(s *grpc.Server, srv CmsServer) {
	s.RegisterService(&_Cms_serviceDesc, srv)
}

func _Cms_Setup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).Setup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/Setup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).Setup(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_IsSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).IsSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/IsSetup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).IsSetup(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).GetPost(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/UpdatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).UpdatePost(ctx, req.(*UpdatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).DeletePost(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_GetPostComments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PostRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CmsServer).GetPostComments(m, &cmsGetPostCommentsServer{stream})
}

type Cms_GetPostCommentsServer interface {
	Send(*Comment) error
	grpc.ServerStream
}

type cmsGetPostCommentsServer struct {
	grpc.ServerStream
}

func (x *cmsGetPostCommentsServer) Send(m *Comment) error {
	return x.ServerStream.SendMsg(m)
}

func _Cms_GetPosts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf1.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CmsServer).GetPosts(m, &cmsGetPostsServer{stream})
}

type Cms_GetPostsServer interface {
	Send(*Post) error
	grpc.ServerStream
}

type cmsGetPostsServer struct {
	grpc.ServerStream
}

func (x *cmsGetPostsServer) Send(m *Post) error {
	return x.ServerStream.SendMsg(m)
}

func _Cms_PublishPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).PublishPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/PublishPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).PublishPost(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_UnPublishPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).UnPublishPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/UnPublishPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).UnPublishPost(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).GetUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).DeleteUser(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_GetUserComments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CmsServer).GetUserComments(m, &cmsGetUserCommentsServer{stream})
}

type Cms_GetUserCommentsServer interface {
	Send(*Comment) error
	grpc.ServerStream
}

type cmsGetUserCommentsServer struct {
	grpc.ServerStream
}

func (x *cmsGetUserCommentsServer) Send(m *Comment) error {
	return x.ServerStream.SendMsg(m)
}

func _Cms_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_GetComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).GetComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/GetComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).GetComment(ctx, req.(*CommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/UpdateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).UpdateComment(ctx, req.(*UpdateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/DeleteComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).DeleteComment(ctx, req.(*CommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cms_GetComments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf1.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CmsServer).GetComments(m, &cmsGetCommentsServer{stream})
}

type Cms_GetCommentsServer interface {
	Send(*Comment) error
	grpc.ServerStream
}

type cmsGetCommentsServer struct {
	grpc.ServerStream
}

func (x *cmsGetCommentsServer) Send(m *Comment) error {
	return x.ServerStream.SendMsg(m)
}

func _Cms_AuthUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmsServer).AuthUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cms.Cms/AuthUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmsServer).AuthUser(ctx, req.(*AuthUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cms_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cms.Cms",
	HandlerType: (*CmsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Setup",
			Handler:    _Cms_Setup_Handler,
		},
		{
			MethodName: "IsSetup",
			Handler:    _Cms_IsSetup_Handler,
		},
		{
			MethodName: "CreatePost",
			Handler:    _Cms_CreatePost_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _Cms_GetPost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _Cms_UpdatePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _Cms_DeletePost_Handler,
		},
		{
			MethodName: "PublishPost",
			Handler:    _Cms_PublishPost_Handler,
		},
		{
			MethodName: "UnPublishPost",
			Handler:    _Cms_UnPublishPost_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _Cms_CreateUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Cms_GetUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _Cms_DeleteUser_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _Cms_CreateComment_Handler,
		},
		{
			MethodName: "GetComment",
			Handler:    _Cms_GetComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _Cms_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _Cms_DeleteComment_Handler,
		},
		{
			MethodName: "AuthUser",
			Handler:    _Cms_AuthUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPostComments",
			Handler:       _Cms_GetPostComments_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetPosts",
			Handler:       _Cms_GetPosts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetUserComments",
			Handler:       _Cms_GetUserComments_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetComments",
			Handler:       _Cms_GetComments_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cms.proto",
}

func init() { proto.RegisterFile("cms.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xce, 0xda, 0x8e, 0x7f, 0x8e, 0xe3, 0xd4, 0x99, 0x86, 0xd4, 0x35, 0x2d, 0x9e, 0x2e, 0x45,
	0xaa, 0xac, 0xc6, 0x6e, 0x13, 0x09, 0x45, 0x05, 0x09, 0xe5, 0xa7, 0x04, 0xab, 0x10, 0x52, 0x37,
	0x69, 0x2b, 0x50, 0x1b, 0x6d, 0x76, 0xa7, 0xf1, 0xaa, 0xeb, 0x9d, 0x65, 0x67, 0x36, 0x89, 0xa9,
	0x2a, 0x59, 0x5c, 0x22, 0xee, 0x78, 0x00, 0x78, 0x07, 0xde, 0x80, 0x07, 0xe0, 0x06, 0xee, 0x2d,
	0x59, 0x5c, 0xf2, 0x10, 0x68, 0x66, 0x7f, 0x6d, 0xc7, 0x4d, 0x55, 0x81, 0x72, 0xb7, 0x33, 0x67,
	0xce, 0x37, 0xdf, 0x77, 0xce, 0x37, 0xb3, 0x03, 0x05, 0xbd, 0xcb, 0x1a, 0x8e, 0x4b, 0x39, 0x45,
	0x69, 0xbd, 0xcb, 0xaa, 0xd7, 0x8e, 0x28, 0x3d, 0xb2, 0x48, 0x53, 0x73, 0xcc, 0xa6, 0x66, 0xdb,
	0x94, 0x6b, 0xdc, 0xa4, 0x76, 0xb0, 0xa4, 0xfa, 0x7e, 0x10, 0x95, 0xa3, 0x43, 0xef, 0x45, 0x93,
	0x74, 0x1d, 0xde, 0x0b, 0x82, 0x1f, 0x8c, 0x07, 0x4f, 0x5c, 0xcd, 0x71, 0x88, 0x1b, 0x26, 0x7f,
	0x7c, 0x64, 0xf2, 0x8e, 0x77, 0xd8, 0xd0, 0x69, 0xb7, 0xd9, 0x3d, 0x31, 0xf9, 0x4b, 0x7a, 0xd2,
	0x3c, 0xa2, 0xcb, 0x32, 0xb8, 0x7c, 0xac, 0x59, 0xa6, 0xa1, 0x71, 0xea, 0xb2, 0x66, 0xf4, 0xe9,
	0xe7, 0xa9, 0xbf, 0x29, 0x90, 0xd9, 0xa5, 0x8c, 0xa3, 0x79, 0x48, 0x99, 0x46, 0x45, 0xc1, 0xca,
	0xad, 0x52, 0x3b, 0x65, 0x1a, 0x68, 0x11, 0x66, 0xb9, 0xc9, 0x2d, 0x52, 0x49, 0x61, 0xe5, 0x56,
	0xa1, 0xed, 0x0f, 0x50, 0x05, 0x72, 0x3a, 0xb5, 0x39, 0xb1, 0x79, 0x25, 0x2d, 0xe7, 0xc3, 0xa1,
	0x8c, 0xb8, 0x44, 0xe3, 0xc4, 0xa8, 0x64, 0x82, 0x88, 0x3f, 0x44, 0x35, 0x28, 0x5a, 0x1a, 0xe3,
	0x07, 0xc4, 0x30, 0x45, 0x74, 0x56, 0x46, 0x41, 0x4c, 0xdd, 0x97, 0x33, 0xe8, 0x1a, 0x14, 0x1c,
	0xef, 0xd0, 0x32, 0x59, 0x87, 0x18, 0x95, 0xac, 0x0c, 0xc7, 0x13, 0x08, 0x41, 0x86, 0x59, 0xde,
	0x51, 0x25, 0x27, 0x03, 0xf2, 0x5b, 0xfd, 0x08, 0x8a, 0x82, 0x74, 0x9b, 0x7c, 0xe7, 0x11, 0xc6,
	0xd1, 0x52, 0xcc, 0x7d, 0x23, 0x3b, 0x1c, 0xd4, 0x52, 0xe5, 0x19, 0xa1, 0x41, 0xfd, 0x4b, 0x81,
	0x85, 0x4d, 0xc9, 0x22, 0xb9, 0xfa, 0x7a, 0xa8, 0x4c, 0x24, 0x14, 0x36, 0x72, 0xc3, 0x41, 0x2d,
	0x7d, 0xda, 0x4f, 0x85, 0x12, 0x3f, 0x8c, 0x25, 0x4a, 0xe9, 0x1b, 0x85, 0xe1, 0xa0, 0x36, 0x7b,
	0xda, 0xef, 0xf7, 0xf3, 0xb1, 0xda, 0x57, 0x01, 0x29, 0x59, 0x84, 0x8d, 0xa3, 0xe1, 0xa0, 0xa6,
	0xd7, 0x9f, 0x6f, 0x51, 0x6c, 0x53, 0x8e, 0x4d, 0x5b, 0xb7, 0x3c, 0x83, 0x60, 0x0d, 0x8b, 0x25,
	0xf8, 0x58, 0xb3, 0x3c, 0x82, 0x4d, 0x1b, 0xf7, 0xa8, 0xe7, 0x62, 0xd7, 0x27, 0xd1, 0xc0, 0x7b,
	0x1d, 0x93, 0xe1, 0x17, 0x26, 0xb1, 0x0c, 0x6c, 0x32, 0x4c, 0x6d, 0xab, 0x87, 0x3d, 0x46, 0x0c,
	0x6c, 0xda, 0x9c, 0xb8, 0xb6, 0x66, 0x59, 0x3d, 0x7c, 0xd8, 0xc3, 0xbc, 0x43, 0x30, 0x23, 0xee,
	0x31, 0x71, 0x1b, 0x7d, 0x65, 0x26, 0x50, 0xff, 0x8f, 0x02, 0x0b, 0xfb, 0x8e, 0x31, 0x26, 0x6b,
	0x4a, 0x11, 0x62, 0xb9, 0xa9, 0xf3, 0xe4, 0xa6, 0xcf, 0x95, 0x9b, 0xb9, 0x08, 0xb9, 0xbf, 0x2a,
	0x90, 0xdb, 0xa4, 0xdd, 0xae, 0x20, 0x32, 0xee, 0xd2, 0xca, 0x58, 0xb3, 0xce, 0xf4, 0x63, 0xfa,
	0x8d, 0x7e, 0xcc, 0x4c, 0xf8, 0xf1, 0x0a, 0xe4, 0x3c, 0x46, 0xdc, 0x03, 0x33, 0x34, 0x6b, 0x56,
	0x0c, 0x5b, 0x32, 0xe0, 0x50, 0xc6, 0x45, 0xc0, 0xb7, 0x69, 0x56, 0x0c, 0x5b, 0x86, 0x7a, 0x0b,
	0xe6, 0x03, 0x86, 0xe7, 0x59, 0xf2, 0x0f, 0x05, 0x16, 0x7d, 0x4b, 0x8e, 0x25, 0xdc, 0x8c, 0x95,
	0xf8, 0xbe, 0x84, 0xe1, 0xa0, 0x96, 0x7d, 0xaa, 0x9c, 0xf6, 0xfb, 0x99, 0x58, 0x15, 0x8d, 0xa9,
	0xf9, 0xed, 0x7c, 0x3c, 0x1c, 0xd4, 0xda, 0x50, 0x7e, 0xfe, 0xad, 0xb6, 0xfc, 0xfd, 0xfa, 0xf2,
	0x37, 0xcf, 0x5e, 0xad, 0xde, 0xbe, 0xbb, 0xf6, 0xfa, 0x66, 0xfd, 0xd3, 0x7d, 0x46, 0x5c, 0xdc,
	0x32, 0x70, 0xd7, 0x63, 0x1c, 0x1f, 0x12, 0xbc, 0xba, 0x7c, 0x77, 0x0d, 0xeb, 0x1d, 0xcd, 0xd5,
	0x74, 0x4e, 0x5c, 0x86, 0x35, 0xdb, 0xc0, 0xba, 0x66, 0xfb, 0xad, 0x08, 0x7b, 0x68, 0x11, 0x2e,
	0x82, 0x4f, 0x95, 0x48, 0x72, 0x2d, 0x96, 0x9c, 0x1e, 0x11, 0x13, 0x4a, 0xdf, 0x83, 0x45, 0xdf,
	0x8b, 0x6f, 0x57, 0x80, 0xa4, 0xce, 0xd4, 0x54, 0x9d, 0xea, 0x8f, 0x0a, 0x64, 0x84, 0x82, 0x44,
	0xc3, 0x0b, 0xe1, 0xb5, 0x44, 0xba, 0x9a, 0x69, 0x85, 0xd7, 0x92, 0x1c, 0xbc, 0x45, 0xb3, 0x35,
	0x9d, 0x9b, 0xc7, 0x24, 0xd9, 0xec, 0x75, 0x39, 0x83, 0x6e, 0x40, 0xc6, 0xa5, 0x16, 0x91, 0x9d,
	0x9e, 0x5f, 0x29, 0x35, 0xc4, 0x95, 0x2d, 0x76, 0x6e, 0x53, 0x8b, 0xb4, 0x65, 0x48, 0xf5, 0xa0,
	0x28, 0x67, 0x02, 0x65, 0x2f, 0x62, 0x4a, 0xff, 0x5b, 0xf9, 0x85, 0x55, 0x7e, 0x8f, 0x6e, 0xaf,
	0x0b, 0xd8, 0x1d, 0xd5, 0x46, 0x0a, 0xed, 0xdf, 0x0a, 0xa2, 0x4b, 0xa9, 0xb0, 0xe6, 0x37, 0x21,
	0xef, 0x68, 0x8c, 0x9d, 0x50, 0x37, 0x28, 0xfa, 0x46, 0x7e, 0x38, 0xa8, 0x65, 0x9e, 0x2a, 0xa7,
	0xab, 0xed, 0x28, 0xa2, 0xea, 0x80, 0x62, 0x0d, 0x4f, 0x4c, 0xde, 0x11, 0x75, 0x45, 0x75, 0xc8,
	0x08, 0x7f, 0x49, 0x19, 0xc5, 0x95, 0x25, 0x59, 0xf4, 0x09, 0xa9, 0x6d, 0xb9, 0x26, 0x6a, 0x50,
	0x6a, 0x7a, 0x83, 0x7e, 0x51, 0xe0, 0xd2, 0xba, 0xc7, 0x3b, 0x17, 0x51, 0xa7, 0x64, 0x19, 0x52,
	0x53, 0xcb, 0x60, 0x43, 0x71, 0x5d, 0xd7, 0x09, 0x63, 0x7b, 0xf4, 0x25, 0xb1, 0xd1, 0x0d, 0x98,
	0xd3, 0xe4, 0xf0, 0x80, 0x8b, 0x71, 0xe0, 0xef, 0xa2, 0x96, 0x58, 0x72, 0x1d, 0x40, 0xc6, 0x0e,
	0x78, 0xcf, 0x09, 0x7f, 0xc2, 0x05, 0x39, 0xb3, 0xd7, 0x73, 0x88, 0x08, 0x93, 0x53, 0xc7, 0x74,
	0x09, 0x3b, 0x30, 0x6d, 0xff, 0x68, 0xb6, 0x0b, 0xc1, 0x4c, 0xcb, 0x56, 0xeb, 0x30, 0x27, 0xb4,
	0xed, 0x06, 0xfb, 0xa3, 0x6a, 0x82, 0xa5, 0xbf, 0x59, 0x34, 0xae, 0xdf, 0x86, 0x7c, 0x58, 0x4f,
	0x54, 0x84, 0xdc, 0xfe, 0xce, 0x83, 0x9d, 0xaf, 0x9f, 0xec, 0x94, 0x67, 0x50, 0x01, 0x66, 0xd7,
	0xb7, 0xbe, 0x6a, 0xed, 0x94, 0x15, 0x94, 0x87, 0xcc, 0xfe, 0xa3, 0xfb, 0xed, 0x72, 0x6a, 0x65,
	0x1b, 0x8a, 0x9b, 0x5d, 0xd6, 0x0a, 0xae, 0x6d, 0xb4, 0x06, 0x97, 0xb6, 0x09, 0x1f, 0xd9, 0xab,
	0x1c, 0xb7, 0xc8, 0xef, 0x45, 0x75, 0x21, 0x9a, 0x09, 0x17, 0xa9, 0x33, 0x2b, 0x9b, 0x90, 0xdb,
	0xec, 0x32, 0xd1, 0x36, 0xb4, 0x06, 0x57, 0xe4, 0x69, 0xd4, 0x38, 0xd9, 0x21, 0x27, 0x52, 0xff,
	0xe7, 0xd4, 0x95, 0xe7, 0xbf, 0x10, 0xa5, 0x56, 0x7d, 0xdc, 0x44, 0x19, 0xd5, 0x99, 0x95, 0x9f,
	0xe6, 0x20, 0xbd, 0xd9, 0x65, 0x68, 0x0b, 0x66, 0x1f, 0x11, 0xee, 0x39, 0x68, 0x8a, 0x97, 0xaa,
	0x13, 0xa4, 0xd4, 0x85, 0x1f, 0xfe, 0xfc, 0xfb, 0xe7, 0x54, 0x51, 0xcd, 0x36, 0x99, 0xc8, 0xbc,
	0xa7, 0xd4, 0xd1, 0x2e, 0xe4, 0x5a, 0x2c, 0xc4, 0xf1, 0x1f, 0x5c, 0x8d, 0xf0, 0xc1, 0xd5, 0xb8,
	0x2f, 0x5e, 0x63, 0xd5, 0xea, 0xc4, 0xfc, 0x06, 0xa5, 0xd6, 0x63, 0xf1, 0xd3, 0x0b, 0x11, 0x51,
	0xa1, 0x69, 0xb2, 0x65, 0x09, 0x8a, 0x5a, 0x00, 0xf1, 0x03, 0x64, 0x84, 0x5c, 0xe2, 0xd7, 0x1d,
	0x90, 0x4b, 0xcc, 0x24, 0xc8, 0x89, 0x6b, 0x96, 0x09, 0x72, 0x9f, 0x40, 0x6e, 0x9b, 0x70, 0x89,
	0x33, 0xb1, 0xbe, 0x5a, 0x88, 0x66, 0xd4, 0xcb, 0x32, 0xb5, 0x84, 0x8a, 0x7e, 0x6a, 0xf3, 0x95,
	0x69, 0xbc, 0x46, 0x7b, 0x00, 0xf1, 0x8b, 0x21, 0xe0, 0x31, 0xf1, 0x84, 0xa8, 0x4e, 0x11, 0xad,
	0x2e, 0x49, 0xc8, 0x72, 0x35, 0x09, 0x29, 0x28, 0x3d, 0x00, 0xd8, 0x22, 0x16, 0x09, 0x50, 0x27,
	0x59, 0x4d, 0xc3, 0x0b, 0x28, 0xd6, 0x47, 0x28, 0x3e, 0x94, 0x4e, 0x12, 0xe9, 0xc1, 0x9f, 0x84,
	0x9d, 0x81, 0x38, 0xe7, 0x57, 0xd0, 0x5f, 0xa0, 0x5e, 0x93, 0x38, 0x4b, 0x68, 0x31, 0x81, 0xd3,
	0xd4, 0x83, 0xec, 0x3b, 0x0a, 0xfa, 0x0c, 0xf2, 0x01, 0x24, 0x9b, 0xda, 0xd0, 0x44, 0xe5, 0xe6,
	0x25, 0x5c, 0x1e, 0x05, 0x45, 0xbf, 0xa3, 0xa0, 0x2f, 0xa1, 0xb8, 0xeb, 0x3f, 0x44, 0xdf, 0x4d,
	0xe1, 0x48, 0xc5, 0xd0, 0x0e, 0x94, 0xf6, 0xed, 0xff, 0x10, 0x2f, 0x32, 0x97, 0x3c, 0x29, 0xef,
	0xe2, 0x7c, 0x71, 0xc1, 0x26, 0xcc, 0x25, 0x71, 0x26, 0x8f, 0x6f, 0x7c, 0x06, 0x13, 0xe6, 0x92,
	0xa9, 0x3e, 0x8f, 0xc8, 0x06, 0x53, 0xf2, 0xcf, 0xb7, 0x41, 0x02, 0xec, 0x61, 0x74, 0xa1, 0x8c,
	0xd9, 0x20, 0x89, 0x38, 0xcd, 0x06, 0x31, 0x4e, 0xd2, 0x06, 0xfb, 0x50, 0x1a, 0x79, 0x72, 0xa1,
	0xab, 0x89, 0x52, 0x8d, 0x3e, 0x5b, 0xaa, 0x97, 0x93, 0xc8, 0x61, 0xc1, 0x16, 0xe5, 0x06, 0xf3,
	0x6a, 0x21, 0x42, 0x15, 0x35, 0xdb, 0x06, 0xd8, 0x26, 0xa1, 0x59, 0xd1, 0x59, 0x89, 0x63, 0x3c,
	0x83, 0x63, 0x84, 0xe6, 0x23, 0x18, 0x5f, 0xf2, 0x33, 0x28, 0x8d, 0x3c, 0xa1, 0x02, 0x7e, 0x67,
	0x3d, 0xab, 0xa6, 0xd6, 0xf2, 0xaa, 0xc4, 0xbe, 0x5c, 0x1d, 0xc3, 0x16, 0x3c, 0xf7, 0xa0, 0xe4,
	0xb7, 0xe7, 0x8d, 0x54, 0xcf, 0x39, 0xfb, 0xf5, 0x71, 0xd2, 0x5f, 0x40, 0x31, 0x56, 0x3f, 0xfd,
	0x78, 0x8d, 0x56, 0x20, 0xbe, 0x21, 0x13, 0xed, 0x69, 0x41, 0x3e, 0xfc, 0x79, 0xa3, 0x45, 0xff,
	0x8e, 0x1f, 0xfd, 0x97, 0x9f, 0x71, 0xf3, 0xbf, 0x27, 0x81, 0x2e, 0xa9, 0xd0, 0xd4, 0x3c, 0xde,
	0x91, 0x7d, 0xbf, 0xa7, 0xd4, 0x0f, 0xb3, 0x72, 0xf7, 0xd5, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x48, 0xb7, 0xb9, 0xd0, 0x79, 0x0f, 0x00, 0x00,
}
