sudo: required
language: go
services:
- docker
go:
- 1.8.5
gobuild_args: "-v -tags=integration"
before_install:
- openssl aes-256-cbc -K $encrypted_5f6b54967430_key -iv $encrypted_5f6b54967430_iv
  -in secrets.tar.enc -out secrets.tar -d
- docker-compose build
install: true
before_deploy:
- tar xvf secrets.tar
deploy:
  provider: gae
  project: learned-stone-189802
  keyfile: client-secret.json
  config: cms/app.yaml
  docker_build: local
  on: develop
  skip_cleanup: true
notifications:
  email: false
