// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cacher.proto

/*
Package cacher is a generated protocol buffer package.

It is generated from these files:
	cacher.proto

It has these top-level messages:
	SetRequest
	GetRequest
	DeleteRequest
*/
package cacher

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import google_protobuf1 "github.com/golang/protobuf/ptypes/wrappers"
import google_protobuf2 "github.com/golang/protobuf/ptypes/duration"

import (
	"context"

	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SetRequest struct {
	Key   string                     `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string                     `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Ttl   *google_protobuf2.Duration `protobuf:"bytes,3,opt,name=ttl" json:"ttl,omitempty"`
}

func (m *SetRequest) Reset()                    { *m = SetRequest{} }
func (m *SetRequest) String() string            { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()               {}
func (*SetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *SetRequest) GetTtl() *google_protobuf2.Duration {
	if m != nil {
		return m.Ttl
	}
	return nil
}

type GetRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeleteRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeleteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*SetRequest)(nil), "cacher.SetRequest")
	proto.RegisterType((*GetRequest)(nil), "cacher.GetRequest")
	proto.RegisterType((*DeleteRequest)(nil), "cacher.DeleteRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Cacher service

type CacherClient interface {
	// Set a key/value pair
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	// Get a value by key
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*google_protobuf1.StringValue, error)
	// Delete a key
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type cacherClient struct {
	cc *grpc.ClientConn
}

func NewCacherClient(cc *grpc.ClientConn) CacherClient {
	return &cacherClient{cc}
}

func (c *cacherClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/cacher.Cacher/Set", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacherClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*google_protobuf1.StringValue, error) {
	out := new(google_protobuf1.StringValue)
	err := grpc.Invoke(ctx, "/cacher.Cacher/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacherClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/cacher.Cacher/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cacher service

type CacherServer interface {
	// Set a key/value pair
	Set(context.Context, *SetRequest) (*google_protobuf.Empty, error)
	// Get a value by key
	Get(context.Context, *GetRequest) (*google_protobuf1.StringValue, error)
	// Delete a key
	Delete(context.Context, *DeleteRequest) (*google_protobuf.Empty, error)
}

func RegisterCacherServer(s *grpc.Server, srv CacherServer) {
	s.RegisterService(&_Cacher_serviceDesc, srv)
}

func _Cacher_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacherServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cacher.Cacher/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacherServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cacher_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacherServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cacher.Cacher/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacherServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cacher_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacherServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cacher.Cacher/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacherServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cacher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cacher.Cacher",
	HandlerType: (*CacherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _Cacher_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Cacher_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Cacher_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cacher.proto",
}

func init() { proto.RegisterFile("cacher.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x50, 0x5d, 0x4b, 0xc3, 0x30,
	0x14, 0xb5, 0x06, 0x0b, 0x5e, 0x15, 0xe4, 0xa2, 0x52, 0xab, 0x8c, 0xd9, 0xa7, 0x81, 0x90, 0xc1,
	0xf6, 0xe4, 0xb3, 0x93, 0xbd, 0xb7, 0xe0, 0x7b, 0x36, 0xaf, 0x75, 0x58, 0x97, 0x98, 0xdd, 0x28,
	0xfb, 0x5d, 0xfe, 0x41, 0x49, 0xb2, 0x31, 0xb5, 0xd4, 0xb7, 0xdc, 0xf3, 0xc1, 0x39, 0x39, 0x70,
	0x3c, 0x57, 0xf3, 0x17, 0xb2, 0xd2, 0x58, 0xcd, 0x1a, 0xd3, 0x78, 0xe5, 0x57, 0xb5, 0xd6, 0x75,
	0x43, 0xc3, 0x80, 0xce, 0xdc, 0xf3, 0x90, 0xde, 0x0c, 0xaf, 0xa3, 0x28, 0xef, 0xfd, 0x25, 0x3f,
	0xad, 0x32, 0x86, 0xec, 0xaa, 0x8b, 0x7f, 0x72, 0x56, 0xf1, 0x42, 0x2f, 0x23, 0x5f, 0x28, 0x80,
	0x8a, 0xb8, 0xa4, 0x77, 0x47, 0x2b, 0xc6, 0x53, 0x10, 0xaf, 0xb4, 0xce, 0x92, 0x7e, 0x32, 0x38,
	0x2c, 0xfd, 0x13, 0xcf, 0xe0, 0xe0, 0x43, 0x35, 0x8e, 0xb2, 0xfd, 0x80, 0xc5, 0x03, 0x6f, 0x41,
	0x30, 0x37, 0x99, 0xe8, 0x27, 0x83, 0xa3, 0xd1, 0xa5, 0x8c, 0x19, 0x72, 0x9b, 0x21, 0x27, 0x9b,
	0x8c, 0xd2, 0xab, 0x8a, 0x1e, 0xc0, 0xf4, 0x9f, 0x88, 0xe2, 0x06, 0x4e, 0x26, 0xd4, 0x10, 0x53,
	0xa7, 0x64, 0xf4, 0x95, 0x40, 0x7a, 0x1f, 0xd6, 0xc0, 0x31, 0x88, 0x8a, 0x18, 0x51, 0x6e, 0xb6,
	0xda, 0xb5, 0xcf, 0x2f, 0x5a, 0x45, 0x1e, 0xfc, 0x52, 0xc5, 0x1e, 0xde, 0x81, 0x98, 0xfe, 0x34,
	0xed, 0xfa, 0xe4, 0xd7, 0x2d, 0x53, 0xc5, 0x76, 0xb1, 0xac, 0x1f, 0xfd, 0x47, 0x83, 0x35, 0x8d,
	0xed, 0xf0, 0x7c, 0xeb, 0xfe, 0xd5, 0xb6, 0x3b, 0x75, 0x96, 0x06, 0x64, 0xfc, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0x65, 0xc2, 0x1f, 0xe8, 0xd7, 0x01, 0x00, 0x00,
}
