version: "3.3"
services:
    cms-server:
        build: ./server
        ports:
            - "10000:10000" #grpc
            - "8181:8080"   #rest
        environment:
            - DB_PASS=${DB_PASS}
        depends_on:
            - cms-db
        volumes:
            - type: bind
              source: ./third_party/wait-for-it/wait-for-it.sh
              target: /usr/local/bin/wait-for-it.sh
        command: ["wait-for-it", "db:3306", "--", "go-wrapper", "run"] 
    cms-db:
        image: mysql:5
        environment:
            - MY_SQL_ROOT_PASSWORD=${DB_PASS}
        volumes:
            - type: bind
              source: ./cms.sql.gz
              target: /docker-entrypoint-initdb.d/cms.sql.gz
